# Generated by Django 5.0.1 on 2024-01-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_application_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
