# Generated by Django 5.0.1 on 2024-01-18 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_application_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "permissions": (
                    ("change_application_status", "Can change application status"),
                    ("change_application_notes", "Can change application notes"),
                )
            },
        ),
    ]
